version: "3.8"
services:
  michi:
    build: .
    image: ghcr.io/pitydah/michi-micro-server:latest
    container_name: michi
    ports:
      - "8096:8096"
    volumes:
      - ./music:/music:ro
      - ./config:/config
      - ./cache:/cache
    environment:
      - MICHI_PORT=8096
      - MICHI_MUSIC_PATH=/music
      - MICHI_DATABASE=sqlite:///config/michi.db
      - MICHI_CACHE_PATH=/cache
      - MICHI_SYNC_NAME=michiserver
    restart: unless-stopped
