services:
  michi-micro-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: michi-micro-server
    ports:
      - "8096:8096"
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - ./music:/music
    environment:
      - TZ=America/Santiago
      - MICHI_PORT=8096
      - MICHI_MUSIC_PATH=/music
      - MICHI_CONFIG_PATH=/config
      - MICHI_CACHE_PATH=/cache
      - MICHI_DATABASE=sqlite:///config/michi.db?mode=rwc
    restart: unless-stopped
