#!/usr/bin/env python3
"""
External Release Evidence Fetcher & Ingester for Michi Micro Server.

Fetches cross-workflow evidence artifacts (e.g. soak-24h, raspberry-pi-physical, casaos-zimaos-real)
generated by dedicated qualification workflows, verifies SHA provenance and authorized producers,
and materializes them into target/release-evidence/ for release gate evaluation.
"""

import argparse
import io
import json
import os
import sys
import urllib.error
import urllib.request
import zipfile
from typing import Dict, Any, Optional

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT_DIR, "scripts"))

from release_evidence import get_head_sha, validate_evidence_artifact

DEFAULT_EXTERNAL_GATES = [
    "soak-24h",
    "raspberry-pi-physical",
    "casaos-zimaos-real",
]

def load_requirements(req_path: str) -> Dict[str, Any]:
    if not os.path.exists(req_path):
        raise FileNotFoundError(f"Gates requirement file not found: {req_path}")
    with open(req_path, "r", encoding="utf-8") as f:
        return json.load(f)

def get_gate_requirement(requirements: Dict[str, Any], gate_id: str) -> Optional[Dict[str, Any]]:
    for g in requirements.get("gates", []):
        if g.get("id") == gate_id:
            return g
    return None

def fetch_artifact_from_local(source_dir: str, gate_id: str, commit_sha: str) -> Optional[Dict[str, Any]]:
    """Look for evidence artifact in a local directory."""
    candidate_names = [
        f"{gate_id}.json",
        f"release-evidence-{gate_id}-{commit_sha}.json",
        f"release-evidence-{gate_id}.json",
    ]
    for name in candidate_names:
        p = os.path.join(source_dir, name)
        if os.path.exists(p):
            try:
                with open(p, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception as e:
                print(f"WARNING: Error reading local artifact {p}: {e}", file=sys.stderr)
    return None

GATE_WORKFLOW_MAP = {
    "soak-24h": {
        "workflow_file": "soak-24h.yml",
        "job": "soak-24h",
    },
    "raspberry-pi-physical": {
        "workflow_file": "rpi-physical.yml",
        "job": "rpi-physical",
    },
    "casaos-zimaos-real": {
        "workflow_file": "zimaos-physical.yml",
        "job": "zimaos-physical",
    },
}

def fetch_artifact_from_github(
    repo: str,
    token: str,
    gate_id: str,
    commit_sha: str,
) -> Optional[Dict[str, Any]]:
    """Fetch and extract artifact from GitHub Actions API, verifying real GitHub workflow origin."""
    headers = {
        "User-Agent": "michi-evidence-fetcher",
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }

    expected_artifact_name = f"release-evidence-{gate_id}-{commit_sha}"
    expected_workflow_spec = GATE_WORKFLOW_MAP.get(gate_id)

    # 1. Paginate artifacts up to 10 pages (1000 artifacts)
    matching_artifacts = []
    page = 1
    while page <= 10:
        api_url = f"https://api.github.com/repos/{repo}/actions/artifacts?per_page=100&page={page}"
        try:
            req = urllib.request.Request(api_url, headers=headers)
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read().decode("utf-8"))
        except Exception as e:
            print(f"WARNING: GitHub API query failed for {repo} on page {page}: {e}", file=sys.stderr)
            break

        page_artifacts = data.get("artifacts", [])
        if not page_artifacts:
            break

        for a in page_artifacts:
            if a.get("expired", False):
                continue
            name = a.get("name", "")
            wf_run = a.get("workflow_run", {})
            run_sha = wf_run.get("head_sha")

            if name == expected_artifact_name:
                matching_artifacts.append(a)
            elif name == f"release-evidence-{gate_id}" and run_sha == commit_sha:
                matching_artifacts.append(a)

        if any(a.get("name") == expected_artifact_name for a in matching_artifacts):
            break

        if len(page_artifacts) < 100:
            break
        page += 1

    if not matching_artifacts:
        return None

    matching_artifacts.sort(key=lambda x: x.get("id", 0), reverse=True)

    # 2. Inspect candidates and verify workflow and job origin
    for candidate in matching_artifacts:
        wf_run = candidate.get("workflow_run", {})
        run_id = wf_run.get("id")
        run_sha = wf_run.get("head_sha")

        if run_sha != commit_sha:
            print(f"  ⚠️ Candidate artifact {candidate.get('id')} has head_sha mismatch: expected {commit_sha}, got {run_sha}", file=sys.stderr)
            continue

        if not run_id:
            print(f"  ⚠️ Candidate artifact {candidate.get('id')} missing workflow_run.id", file=sys.stderr)
            continue

        run_url = f"https://api.github.com/repos/{repo}/actions/runs/{run_id}"
        try:
            req = urllib.request.Request(run_url, headers=headers)
            with urllib.request.urlopen(req, timeout=15) as resp:
                run_data = json.loads(resp.read().decode("utf-8"))
        except Exception as e:
            print(f"  ⚠️ Failed to inspect workflow run {run_id}: {e}", file=sys.stderr)
            continue

        if run_data.get("conclusion") != "success":
            print(f"  ⚠️ Workflow run {run_id} did not conclude with success (conclusion: {run_data.get('conclusion')})", file=sys.stderr)
            continue

        run_path = run_data.get("path", "")
        if expected_workflow_spec:
            expected_wf_file = expected_workflow_spec["workflow_file"]
            if not run_path.endswith(expected_wf_file):
                print(f"  ⚠️ Workflow run {run_id} path '{run_path}' does not match expected '{expected_wf_file}'", file=sys.stderr)
                continue

            # Verify authorized job in the run
            jobs_url = f"https://api.github.com/repos/{repo}/actions/runs/{run_id}/jobs?per_page=100"
            try:
                req = urllib.request.Request(jobs_url, headers=headers)
                with urllib.request.urlopen(req, timeout=15) as resp:
                    jobs_data = json.loads(resp.read().decode("utf-8"))
                jobs = jobs_data.get("jobs", [])
                expected_job_name = expected_workflow_spec["job"]
                matching_job = next((j for j in jobs if j.get("name") == expected_job_name), None)
                if not matching_job:
                    print(f"  ⚠️ Workflow run {run_id} missing expected job '{expected_job_name}'", file=sys.stderr)
                    continue
                if matching_job.get("conclusion") != "success":
                    print(f"  ⚠️ Job '{expected_job_name}' in run {run_id} conclusion was '{matching_job.get('conclusion')}' (not success)", file=sys.stderr)
                    continue
            except Exception as e:
                print(f"  ⚠️ Could not verify jobs in run {run_id}: {e}", file=sys.stderr)
                continue

        # 3. Download and extract artifact
        art_id = candidate["id"]
        download_url = f"https://api.github.com/repos/{repo}/actions/artifacts/{art_id}/zip"
        try:
            req = urllib.request.Request(download_url, headers=headers)
            with urllib.request.urlopen(req, timeout=30) as resp:
                zip_bytes = resp.read()
        except Exception as e:
            print(f"  ⚠️ Failed to download artifact {art_id} from {download_url}: {e}", file=sys.stderr)
            continue

        try:
            with zipfile.ZipFile(io.BytesIO(zip_bytes)) as z:
                for fname in z.namelist():
                    if fname.endswith(".json"):
                        with z.open(fname) as jf:
                            artifact_json = json.loads(jf.read().decode("utf-8"))
                            return artifact_json
        except Exception as e:
            print(f"  ⚠️ Failed to parse zip archive for artifact {art_id}: {e}", file=sys.stderr)
            continue

    return None

def ingest_evidence(
    gate_id: str,
    raw_data: Dict[str, Any],
    commit_sha: str,
    requirement: Dict[str, Any],
    output_dir: str,
) -> bool:
    """Validate artifact provenance and save to output directory."""
    status, detail = validate_evidence_artifact(raw_data, commit_sha, requirement)
    if status in ("STALE", "INVALID_EVIDENCE"):
        print(f"  ❌ Gate {gate_id}: Rejected ({status}: {detail})", file=sys.stderr)
        return False

    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, f"{gate_id}.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(raw_data, f, indent=2)
    print(f"  ✓ Gate {gate_id}: Validated ({status}: {detail}) -> {out_path}")
    return True

def main():
    parser = argparse.ArgumentParser(description="Fetch and ingest cross-workflow release evidence")
    parser.add_argument("--commit-sha", default=None, help="Target commit SHA (default: git rev-parse HEAD)")
    parser.add_argument("--repo", default=os.getenv("GITHUB_REPOSITORY", "pitydah/michi-micro-server"), help="GitHub repository owner/repo")
    parser.add_argument("--token", default=os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN"), help="GitHub API Token")
    parser.add_argument("--gates", nargs="+", default=DEFAULT_EXTERNAL_GATES, help="List of gate IDs to fetch")
    parser.add_argument("--output-dir", default=os.path.join(ROOT_DIR, "target", "release-evidence"), help="Output directory")
    parser.add_argument("--requirements", default=os.path.join(ROOT_DIR, "release", "gates.json"), help="Gates requirement JSON file")
    parser.add_argument("--source-dir", default=None, help="Local directory to load artifacts from instead of GitHub API")
    parser.add_argument("--allow-missing", action="store_true", help="Do not exit with error if external evidence is missing")
    args = parser.parse_args()

    commit_sha = args.commit_sha or get_head_sha()
    print(f"Fetching external release evidence for commit {commit_sha[:8]}...")
    print(f"Target gates: {args.gates}")

    try:
        requirements = load_requirements(args.requirements)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    missing = []
    invalid = []
    success_count = 0

    for gate_id in args.gates:
        req = get_gate_requirement(requirements, gate_id)
        if not req:
            print(f"WARNING: Gate {gate_id} not defined in requirements; skipping", file=sys.stderr)
            continue

        data = None
        if args.source_dir and os.path.exists(args.source_dir):
            data = fetch_artifact_from_local(args.source_dir, gate_id, commit_sha)

        if not data and args.token and args.repo:
            data = fetch_artifact_from_github(args.repo, args.token, gate_id, commit_sha)

        if not data:
            print(f"  ⚠️ Gate {gate_id}: No evidence artifact found")
            missing.append(gate_id)
            continue

        ok = ingest_evidence(gate_id, data, commit_sha, req, args.output_dir)
        if ok:
            success_count += 1
        else:
            invalid.append(gate_id)

    print(f"\nExternal evidence fetch summary: {success_count} ingested, {len(invalid)} invalid, {len(missing)} missing.")

    if invalid:
        print(f"ERROR: {len(invalid)} artifact(s) failed validation: {invalid}", file=sys.stderr)
        sys.exit(1)

    if missing and not args.allow_missing:
        print(f"ERROR: {len(missing)} required artifact(s) missing: {missing}", file=sys.stderr)
        sys.exit(1)

    sys.exit(0)

if __name__ == "__main__":
    main()
