version: "3.8"

services:
  michi-micro-server:
    image: pitydah/michi-micro-server:latest
    container_name: michi-micro-server
    ports:
      - "8096:8096"
    volumes:
      - ${CONFIG_PATH}:/config
      - ${CACHE_PATH}:/cache
      - ${MUSIC_PATH}:/music
    environment:
      - TZ=${TZ}
      - MICHI_PORT=8096
      - MICHI_MUSIC_PATH=/music
      - MICHI_CONFIG_PATH=/config
      - MICHI_CACHE_PATH=/cache
      - MICHI_DATABASE=sqlite:///config/michi.db?mode=rwc
    restart: unless-stopped
